version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: tmpauth:latest
    container_name: tmpauth
    restart: always
    volumes:
      - .:/app/src
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - pg_db

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  pg_db:
    image: postgres:13
    container_name: tmpauth-pg-db
    env_file:
      - ./.env
    volumes:
      - tmpauth-pd-db-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

volumes:
  tmpauth-pd-db-data:
    name: tmpauth-pg-db-data
