version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: booking:latest
    container_name: cafe_booking
    restart: always
    volumes:
      - .:/app/src
    ports:
      - 8000:8000
    env_file:
      - ../.env
    depends_on:
      - pg_db

  pg_db:
    image: postgres:13
    container_name: booking-pg-db
    env_file:
      - ../.env
    volumes:
      - booking-pd-db-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5435:5432"

volumes:
  booking-pd-db-data:
    name: booking-pg-db-data
