version: '3.7'

x-common-variables: &common-env-variables
  TMPAUTH_SQLALCHEMY_HOST: tmpauth-pg-db
  TMPAUTH_SQLALCHEMY_PORT: ${TMPAUTH_SQLALCHEMY_PORT}
  TMPAUTH_SQLALCHEMY_USERNAME: ${TMPAUTH_SQLALCHEMY_USERNAME}
  TMPAUTH_SQLALCHEMY_PASSWORD: ${TMPAUTH_SQLALCHEMY_PASSWORD}
  TMPAUTH_SQLALCHEMY_BASE_NAME: ${TMPAUTH_SQLALCHEMY_BASE_NAME}

  TMPAUTH_AUTH_RESET_PASSWORD_TOKEN_SECRET: ${TMPAUTH_AUTH_RESET_PASSWORD_TOKEN_SECRET}
  TMPAUTH_AUTH_VERIFICATION_TOKEN_SECRET: ${TMPAUTH_AUTH_VERIFICATION_TOKEN_SECRET}

services:
  migrate:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: tmpauth:latest
    container_name: tmpauth-migrate
    restart: "no"
    env_file:
      - ./.env
    environment: *common-env-variables
    depends_on:
      - pg_db
    command: alembic upgrade head
    volumes:
      - .:/app/src

  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: tmpauth:latest
    container_name: tmpauth
    restart: always
    env_file:
      - ./.env
    volumes:
      - .:/app/src
    ports:
      - 8000:8000
    depends_on:
      - pg_db
      - migrate
    environment: *common-env-variables

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  pg_db:
    image: postgres:13
    container_name: tmpauth-pg-db
    volumes:
      - tmpauth-pd-db-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  tmpauth-pd-db-data:
    name: tmpauth-pg-db-data
